### ISSUE TITLE
TSError: ⨯ Unable to compile TypeScript

### ISSUE THREAD

**Issue by dipenpatel235** [brakmic/BiB#3]
node -v  v8.11.3
npm -v 5.6.0

[root@centos-2gb-nbg1-1 BiB]# npm run start:server

> bib@1.2.4 start:server /root/BiB
> ts-node ./src/server/server.ts

/root/BiB/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
src/server/api/database/db.client.ts (994,29): Argument of type 'undefined[]' is not assignable to parameter of type 'T | PromiseLike<T>'.
  Type 'undefined[]' is not assignable to type 'PromiseLike<T>'.
    Property 'then' is missing in type 'undefined[]'. (2345)
src/server/api/database/db.client.ts (999,29): Argument of type 'any[]' is not assignable to parameter of type 'T | PromiseLike<T>'.
  Type 'any[]' is not assignable to type 'PromiseLike<T>'.
    Property 'then' is missing in type 'any[]'. (2345)
    at getOutput (/root/BiB/node_modules/ts-node/src/index.ts:307:15)
    at /root/BiB/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/root/BiB/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/root/BiB/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/root/BiB/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bib@1.2.4 start:server: `ts-node ./src/server/server.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bib@1.2.4 start:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-02T11_30_26_021Z-debug.log

**Comment by brakmic** [comment]
Check via google, there are many entries for that. Here one issue from GitHub:

https://github.com/Microsoft/TypeScript/issues/14425

**Comment by dipenpatel235** [comment]
Okey
i will check it and update you

**Comment by dipenpatel235** [comment]
anyway i am not success on fix that error because i have not enough skill to fix issue in java script

**Comment by brakmic** [comment]
ok !
